# Generated by Django 5.1.1 on 2024-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_posts', '0002_instagramaccount_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='url',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='photo',
            field=models.ImageField(default=1, upload_to='instagram/user_post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/user_photos'),
        ),
    ]
